config/routes.rb
Rails.application.routes.draw do



 #首页
  root 'static_pages#home'
  
  # 给路由定一个别名
  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  # 用户登录模块
  get 'signup' => 'users#new'

  resources :users

  # 登录路由
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'


  # 邮件激活
  resources :account_activations, only: [:edit]

end

app/models/cloth.rb
class Cloth < ActiveRecord::Base
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  # 设定默认排序
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length:{ maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
	# 为了避免索引在某些数据区分大小写的问题 在存数据库时 统一将email存成小写  再存入数据库之前调用
	before_save :downcase_email
	# 新建对象之前 为user对象分配一个激活令牌
	before_create :create_activation_digest 
	attr_accessor :remember_token, :activation_token
	# 验证规则
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence:true, length: { maximum:200 }, format: { with:VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }, allow_blank: true # 允许修改时跳过密码的长度认证
	has_secure_password
	has_many :microposts, dependent: :destroy

	# 返回指定字符串的哈希摘要
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# 返回记忆令牌
	def self.new_token
		SecureRandom.urlsafe_base64
	end

	# 实现持久会话 将会话信息存入数据库
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(self.remember_token))
	end

	# 如果指定的令牌和摘要匹配 返回ture
	def authenticated?(attribute, token)
		# send方法会返回这个对象本身的方法返回值 如user.length 相当于 user.send('length') 由于再User模型内所以self.send可以简写为send
		digest = send("#{ attribute }_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

	# 忘记用户
	def forget
		update_attribute(:remember_digest, nil)
	end

	# 将邮箱地址转化为为小写
	def downcase_email
		self.email = email.downcase
	end

	# 为用户对象分配激活令牌
	def create_activation_digest
		self.activation_token = User.new_token
		self.activation_digest = User.digest(activation_token)
	end

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  # 验证邮箱通过
  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.update_attribute(:activated, true)
      user.update_attribute(:activated_at, Time.zone.now)
      log_in user
      flash[:success] = '激活成功'
      redirect_to user
    else
      flash[:danger] = '无效链接'
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # 引入session_help
  include SessionHelper
  def index
  	render text: 'hello world'
  end	
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  # 添加方法
  def create
  	# 查找用户  将用户设置为实例变量 是为了在单元测试中获取 user的虚拟属性（类属性）
  	@user = User.find_by(email: params[:session][:email].downcase)
  	if @user && @user.authenticate(params[:session][:password])
      if @user.activated?
    		# 将用户信息存到session中
    		log_in @user
        # 是否选择 记住我 操作
        params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
    		# 登录成功 重定向到用户页面
    		redirect_back_or @user
      else
        message = '账号未激活，请检查邮箱'
        flash[:warning] = message
        redirect_to root_url
      end
  	else
  		# 错误信息闪现 .now方法是在render重新渲染专用的闪现方法 可以避免闪现消息在跳转其他页面时不消失的bug
  		flash.now[:danger] = '邮箱/密码错误'
  		render 'new'
  	end
  end

  def destroy
    # 只有在用户登录的情况下才能登出
  	log_out if logged_in?
  	redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	# render text: 'hello'
    User.all
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  # 事前过滤器 这个过滤器表示在使用edit update方法前 要调用logged_in_user方法
  before_action :logged_in_user, only:[:edit, :update, :index, :destroy]
  # 验证是否为正确的用户登录
  before_action :correct_user, only:[:edit, :update]
  # 删除功能只能有管理员来操作
  before_action :admin_user, only:[:destroy]

  def new

	@user = User.new

  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = '删除成功'
    redirect_to users_url
  end

  def index

    # 实现分页功能
    @users = User.paginate(page: params[:page], per_page: 10)

  end

  def create
  	# render text: 'cc'
  	# @user = User.new(params[:user])  如果没有指定允许传入的字段 是无法直接使用这种方式进行初始化类
  	@user = User.new(user_params)
  	 # debugger
  	if @user.save
      # 发送激活邮件
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = '请检查你的邮箱'
      # 跳转到首页
      redirect_to root_url
  	else
  		render 'new'
  	end
  end


  def show
  	@user = User.find(params[:id])

@microposts = @user.microposts.paginate(page: params[:page])
  end

  def edit
    # 获取被修改用户
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # 处理更新成功的情况
      flash[:success] = "更改成功"
      redirect_to @user
      else
        # 更新失败 返回编辑页面
        render 'edit'
    end
  end

  # 获取注册用户的注册信息
  private

  	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)

  	end
  
  # 确保用户已经登录过
  def logged_in_user
    # 如果没有登录过 返回错误信息 并且重定向
    unless logged_in?
      store_location
      flash[:danger] = '请登录'
      redirect_to login_path
    end
  end

  # 确保为正确的用户
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # 确保为管理员用户
  def admin_user
    redirect_to root_url unless current_user.admin?
  end

end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	# 根据所在页面返回完整的标题
	def full_title(page_title = '')
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
	# 将用户信息写入session
	def log_in(user)
		# rails自带的存session方法
		session[:user_id] = user.id
	end

	# 获取当前登录用户信息 （如果有）
	def current_user
		# 如果session中存有用户信息
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
       # raise  #调用这个方法后 如果单元测试覆盖到这部分代码 那么会抛出异常 测试通过 代表没有覆盖部分代码
			user = User.find_by(id: user_id)
			if user && user.authenticated?(:remember, cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end

	end

	# 判断用户是否已经登录
	def logged_in?
		!current_user.nil?
	end

	# 登出方法
	def log_out
    forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	# 保存记忆令牌
	def remember(user)
		# 将记忆令牌存入数据库
		user.remember
		# 将用户Id和remember_token 加密后 存入cookie
		cookies.permanent.signed[:user_id] = user.id  #permanet是永久的意思 cookies指定时可以指定expire
		cookies.permanent[:remember_token] = user.remember_token
	end

  # 忘记用户
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 如果指定用户是当前用户 返回true
  def current_user?(user)
  	user == current_user 
  end

  # 重定向到存储的地址 或默认的地址
  def redirect_back_or(default)
  	redirect_to (session[:forwarding_url] || default)
  	session.delete(:forwarding_url)
  end

  # 存储以后需要获取的地址
  def store_location
  	session[:forwarding_url] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# 返回指定用户的 Gravatar
	# 这是一个免费服务 让用户上传图片 并将其关联到邮箱url上
	def gravatar_for(user, options = { size:80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?"
		image_tag gravatar_url, alt: user.name, class: "gravatar"
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
      <small>
        The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
      </small>
<nav> <ul>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><a href="http://news.railstutorial.org/">News</a></li>
</ul> </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
            <div class="container">
            	<%= link_to "sample app", root_path, id: "logo" %>
            	<nav>
              		<ul class="nav navbar-nav pull-right">
              			<li><%= link_to "Home", root_path %></li>
              			<li><%= link_to 'Help', help_path %></li>
                    <% if logged_in? %>
                      <li><%= link_to 'User', users_path %></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Account <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li><%= link_to 'Profile', current_user %></li>
                        <li><%= link_to 'Settiong', edit_user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li>
                          <%= link_to 'Logout', logout_path, method: 'delete' %>
                        </li>
                      </ul> 
                    </li>
                      <% else %>
                      <li><%= link_to 'Login', login_path %></li>
                    <% end %>
					</ul> 
				</nav>
          	</div>
        </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag 'application', media: 'all',
                                               'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- 引入 /views/layouts/_shim.html.erb -->
  <%= render 'layouts/shim' %>
    </head>
    <body>
    <%= render 'layouts/header' %>   
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
			<%= yield %> 
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
		</div>
     </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
      <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
      <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
      <span class="content"><%= micropost.content %></span>
      <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
      </span>
</li>

app/views/session/new.html.erb
 <% provide(:title, "Log in") %>
    <h1>Log in</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
      	<%= form_for(:session, url: login_path) do |f| %>
			<%= f.label :emal %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

      <%= f.label :remember_me, class: 'checkout inline' do %>
      <%= f.check_box :remember_me %>
        <span>记住我</span>
      <% end %>

			<%= f.submit 'Login', class: "btn btn-primary" %>
      	<% end %>
      	 <p>New user? <%= link_to "Sign up now!", signup_path %></p>
      </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %> 
<div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@user.errors.count, "error") %>.
</div>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li> <% end %>
</ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About</h1> <p>
This is the home page for the
<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
</p> 

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
  <p>
      Contact the Ruby on Rails Tutorial about the sample app at the
      <a href="http://www.railstutorial.org/#contact">contact page</a>.
      
    </p>
</p> 

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Sample App</h1> <p>
This is the home page for the
<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
</p> 

app/views/static_pages/home.html.erb
<%= provide(:title, 'Home') %>
<!-- <% %>只执行代码 <%= %>执行代码并把代码结果插入到页面中 -->
 <div class="center jumbotron">
      <h1>Welcome to the Sample App</h1>
      <h2>
        This is the home page for the
        <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application.
</h2>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>
    <%= link_to image_tag('rails.png', alt: 'Rails logo'),
    								   'http://rubyonrails.org/' %>

app/views/users/_field.html.erb
 <%= render 'shared/error_messages' %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %> 􏱙􏱚􏱛􏱜

app/views/users/_user.html.erb
<li>
        <%= gravatar_for user, size: 50 %>
        <%= link_to user.name, user %>
        <% if current_user.admin? && !current_user?(user) %>
          | <%= link_to '删除', user, method: 'delete', data: { confirm: '确定删除吗' } %>
        <% end %>
</li>

app/views/users/edit.html.erb
  <% provide(:title, "Edit user") %>
    <h1>Update your profile</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">

<%= form_for(@user) do |f| %>
<%= render 'field', f: f %>
<%= f.submit "Save changes", class: "btn btn-primary" %> 
<% end %>
        <div class="gravatar_edit">
          <%= gravatar_for @user %>
          <a href="http://gravatar.com/emails" target="_blank">change</a>
        </div>
      </div>
    </div>

app/views/users/index.html.erb
 <% provide(:title, 'All users') %>
    <h1>All users</h1>
    <ul class="users">
      <% @users.each do |user| %>
      <%= render user %>
      <% end %>
    </ul>
    <%= will_paginate %>

app/views/users/new.html.erb
    <% provide(:title, 'Sign up') %>
    <h1>Sign up</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %> 
    <%= render 'field', f: f %>
	<%= f.submit "Create my account", class: "btn btn-primary" %> <% end %>
      </div>
    </div>

app/views/users/show.html.erb
    <% provide(:title, @user.name) %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
<h1>
            <%= gravatar_for @user %>
            <%= @user.name %>
          </h1>
        </section>
      </aside>
       <div class="col-md-8">

     
<% if @user.microposts.any? %>
<h3>Microposts (<%= @user.microposts.count %>)</h3> <ol class="microposts">
            <%= render @microposts %>
          </ol>
<%= will_paginate @microposts %> <% end %>
</div>
</div>